-- MySQL Script generated by MySQL Workbench
-- Tue May  9 00:13:56 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gaming_project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gaming_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gaming_project` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `gaming_project` ;

-- -----------------------------------------------------
-- Table `gaming_project`.`df_enero_game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gaming_project`.`df_enero_game` (
  `Top` INT NULL DEFAULT NULL,
  `PEGI` TEXT NULL DEFAULT NULL,
  `Juego` TEXT NULL DEFAULT NULL,
  `Plataforma` TEXT NULL DEFAULT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gaming_project`.`game_sales_feb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gaming_project`.`game_sales_feb` (
  `Top` INT NULL DEFAULT NULL,
  `PEGI` TEXT NULL DEFAULT NULL,
  `Juego` TEXT NULL DEFAULT NULL,
  `Plataforma` TEXT NULL DEFAULT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gaming_project`.`games_sales_marzo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gaming_project`.`games_sales_marzo` (
  `Top` INT NULL DEFAULT NULL,
  `PEGI` TEXT NULL DEFAULT NULL,
  `Juego` TEXT NULL DEFAULT NULL,
  `Plataforma` TEXT NULL DEFAULT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gaming_project`.`noticias_gaming`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gaming_project`.`noticias_gaming` (
  `titulo` TEXT NULL DEFAULT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `Enlace` TEXT NULL DEFAULT NULL,
  `fecha_publicacion` TEXT NULL DEFAULT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gaming_project`.`games_twich`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gaming_project`.`games_twich` (
  `Juego` TEXT NULL DEFAULT NULL,
  `Viewer Hours` TEXT NULL DEFAULT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `df_enero_game_id` INT NOT NULL,
  `game_sales_feb_id` INT NOT NULL,
  `games_sales_marzo_id` INT NOT NULL,
  `noticias_gaming_id` INT NOT NULL,
  PRIMARY KEY (`id`, `df_enero_game_id`, `game_sales_feb_id`, `games_sales_marzo_id`, `noticias_gaming_id`),
  INDEX `fk_games_twich_df_enero_game_idx` (`df_enero_game_id` ASC) VISIBLE,
  INDEX `fk_games_twich_game_sales_feb1_idx` (`game_sales_feb_id` ASC) VISIBLE,
  INDEX `fk_games_twich_games_sales_marzo1_idx` (`games_sales_marzo_id` ASC) VISIBLE,
  INDEX `fk_games_twich_noticias_gaming1_idx` (`noticias_gaming_id` ASC) VISIBLE,
  CONSTRAINT `fk_games_twich_df_enero_game`
    FOREIGN KEY (`df_enero_game_id`)
    REFERENCES `gaming_project`.`df_enero_game` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_games_twich_game_sales_feb1`
    FOREIGN KEY (`game_sales_feb_id`)
    REFERENCES `gaming_project`.`game_sales_feb` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_games_twich_games_sales_marzo1`
    FOREIGN KEY (`games_sales_marzo_id`)
    REFERENCES `gaming_project`.`games_sales_marzo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_games_twich_noticias_gaming1`
    FOREIGN KEY (`noticias_gaming_id`)
    REFERENCES `gaming_project`.`noticias_gaming` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 51
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
